# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.GameSession')),
            ],
        ),
        migrations.CreateModel(
            name='SmartDice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_number', models.IntegerField()),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.GameSession')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='active_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.SessionUser'),
        ),
    ]
