# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_sessionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.GameSession'),
        ),
    ]
