# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171218_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdice',
            name='battery',
            field=models.IntegerField(default=100),
        ),
    ]
